image: Visual Studio 2017

platform:
  - x64

cache:
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 12 x64
  - npm ci

build_script:
  - npm run build

test_script:
  - npm run test

after_test:
  - npm run release
