language: node_js

node_js: "node"

os: linux

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages

before_script:
  - npm install -g elm
  - yarn build

script:
  - yarn dist
