# based on: https://github.com/dwyl/learn-travis/issues/31
language: node_js

node_js: "node"

os: linux

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - sysconfcpus
    - $HOME/.npm # https://stackoverflow.com/a/42523517/1148249

before_script:
  - npm install -g elm
  - yarn build

script:
  - yarn dist
